print("Thank you for using KohlsLite.")
print("----------COMMANDS----------")

print("-----------ANTIS-----------")
print("antiblind - if you are blinded it'll remove the effect")
print("anticlone - if you are cloned it'll remove the clone")
print("antifire - if you are fired/bonfired it'll unfire you")
print("antifreeze - if you are frozen it'll thaw you")
print("antifly - if you are flied it'll unfly you")
print("antijail - if you are jailed it'll unjail you")
print("antikill - if your health is 0 then you'll reset")
print("antipunish - if you are punished it'll unpunish you")
print("antirocket - if you are rocketed it'll unrocket you")
print("antiseizure - if you are seizured it'll unseizure you")
print("antismoke - if you are smoked it'll unsmoke you")
print("antisparkles - if you are sparkled it'll unsparkle you")
print("antispeed - if you are sped it'll reset your speed to 16")
print("antiswag - if you are swagged it'll unswag you")
print("antimessage - if you are messaged by pm/m/h it'll remove the effect")
print("You are able to apply these to the following users:
print("Yourself, All, Others")

print("---------More ANTIS----------")
print("antiattach - prevent people attaching")
print("antiattach2 - stops people attaching with ivory")
print("nok/noobbykill - stops the obby bricks killing you")
print("antigear - stops people from using gears")
print("anticrash - stops people from crashing with gears")
print("anticrash2 - stops people from crashing with gears")
print("anticrash3 - stops people from crashing with gears")

print("-----------TELEPORTS---------")
print("house - teleport to the house")
print("spawn - teleport to spawn")

print("--------PAD RELATED--------")
print("perm - have a permanent admin pad")
print("perm2 - have a permanent admin pad")
print("lg - all pads permanently taken by you")
print("lg2 - all pads permanently taken by you")
print("regen - regen admin pads without clicking the regen pad")
print("spamregen - constantly regen admin pads without clicking the regen pad")

print("---------CRASHES--------")
print("vgcrash - a fast vampire vanquisher crash")
print("dcrash - a crash involving clones and the dog command")
print("fcrash - a crash involving clones and the freeze command")

print("---------SERVER---------")
print("serverlock/slock - punish all users, will auto punish anyone trying to bypass")
print("whitelist/wl - protect some users from the slock")
print("blacklist/bl - slock certain users")
print("privann - announcement a message without your username")
print("welcome - auto welcome and leave message")

print("--------DETECTIONS---------")
print("noob - anyone using :poop or ;fly  or commands like that get roasted")
print("cysd - detect users using /c system or /w")
print("logd - detect users using logs")

print("---------MUSIC STUFF-------")
print("gmusic - playsaved music ids from a list")
print("musicid - check music id of current music")
print("volume - set the volume of the music")
print("stopmusic/pause - pause the music")
print("startmusic/play - play the music")
print("volumern - check the current volume")
print("rgmusic - pick a random saved music id")
print("mnext - skip to the next music id")
print("mprev - play the previous music id")
  
print("-----MORE MUSIC STUFF-----")
print("mmo - play your music id only")
print("mmoid - set the music id for mmo")
print("musicon - turns mmo off, but keeps the id")
print("musicoff - mmo works again!")
print("antimusic - stops music from starting")

print("---------SETTINGS--------")
print("prefix - change the prefix")
